name: Build Kernel

permissions:
  contents: write
  actions: write

on:
  workflow_call:
  workflow_dispatch:

jobs:
  # OnePlus 8 (LineageOS 23.2)
  build-oneplus-8-lineageos23-a16:
    name: "OnePlus 8 (LineageOS 23.2 Android 16) (ReSukiSU+SUSFS v2.2.0)"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-oneplus-8-los23-a16.yml
    secrets: inherit

  # OnePlus 8 (Anomaly-KernelV2)
  build-oneplus-8-Anomaly-KernelV2-a16:
    name: "OnePlus 8 (Anomaly-KernelV2 Android 16) (ReSukiSU+SUSFS v2.2.0)"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/main.yml
    secrets: inherit
